Make Exclusive locks interruptible by async exceptions
takano-akio/filelock pull request #7
Opened 2019-04-23 11:27 UTC by nh2

Hi Akio,

this fixes #6, making this package useful in conjunction with `timeout` and `async`.

See added comments for details.

Greetings,
Niklas

2019-05-02 08:50 UTC, takano-akio requested changes
Thanks for the patch! I made a few comments.

2019-05-02 08:50 UTC, takano-akio commented on System/FileLock/Internal/Flock.hsc
> +              E.interruptible yield
In my tests, instead of `E.interruptible yield`, `E.allowInterrupt` seems sufficient. Do you have a specific test case that doesn't work with `E.allowInterrupt`?

Here is my code https://github.com/takano-akio/filelock/tree/interrupt-test

2019-05-02 08:50 UTC, takano-akio commented on System/FileLock/Internal/Flock.hsc
> +-- when used in conjunction with `LOCK_NB`.
`interruptible` makes a difference when it's *not* used with `LOCK_NB`, right?

2020-02-10 02:22 UTC, nh2 commented on System/FileLock/Internal/Flock.hsc
> +-- when used in conjunction with `LOCK_NB`.
Oh right. I've fixed the message.

2020-02-10 02:50 UTC, nh2 commented on System/FileLock/Internal/Flock.hsc
> +              E.interruptible yield
I think it makes a difference in the non-threaded runtime, see https://gitlab.haskell.org/ghc/ghc/issues/8684#note_142826 and the following comment.

If in your test you remove the `-threaded` from the test suite, then the test will hang with both implementations; but in the `interruptible yield` implementation, sending `SIGINT` or pressing Ctrl+C will allow the program to make progress / terminate as expected, while in the `allowInterrupt` implementation, it will need two `SIGINT` or Ctrl+C's (which kills the GHC runtime), thus showing a slightly worse termination behaviour

What do you think?

2020-06-27 00:53 UTC, nh2 commented on System/FileLock/Internal/Flock.hsc
> +              E.interruptible yield
Another short ping :)

2020-06-30 10:47 UTC, merged

2020-06-30 10:48 UTC, takano-akio commented
Merged, thanks for your patience!

2020-06-30 11:00 UTC, takano-akio commented
Uploaded 0.1.1.5 to Hackage.

2020-07-03 19:37 UTC, nh2 commented
Thanks!